# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 2.0.1"

$cpus   = ENV.fetch("MADOCS_VAGRANT_CPUS", "1")
$memory = ENV.fetch("MADOCS_VAGRANT_MEMORY", "1024")
$hostname = ENV.fetch("MADOCS_VAGRANT_HOSTNAME", "madocs")
$virtualBoxDescription = ENV.fetch("MADOC_VAGRANT_VIRTUALBOXDESCRIPTION", "madocs")

# Available boxes are 'ubuntu2', ubuntu/bionic64'

$vagrantBox = ENV.fetch("ubuntu2", "ubuntu2")

# vagrant is the main user
$vagrantUser = "vagrant"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "virtualbox" do |v|
    v.name = "madocsubuntu"
  end

  config.vm.hostname = $hostname

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = $vagrantBox

  # Configure home directory
  home_dir = "/home/" + $vagrantUser

  # Configure sync directory
  config.vm.synced_folder ".", home_dir + "/madoc"

  config.vm.network :forwarded_port, guest: 8000, host: 8000 # Apache
  config.vm.network :forwarded_port, guest: 8080, host: 8080 # Tomcat
  
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", $memory]
    vb.customize ["modifyvm", :id, "--cpus", $cpus]
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision-playbook.yml"
  end
end